fix: yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -31,19 +31,20 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
       - name: Set up Node
-        uses: actions/setup-node@v3 
+        uses: actions/setup-node@v4
         with:
           node-version: 22.4
           cache: 'npm'
-      - name: Clean npm cache
-        run: npm cache clean --force # 清理 npm 缓存
+      # - name: Clean npm cache
+      #   run: npm cache clean --force # 清理 npm 缓存
       - name: Install dependencies
-        run: |
-          npm ci --legacy-peer-deps || { echo 'npm ci failed'; exit 1; } # 使用 npm ci 安装依赖
-      - name: Clean dist directory
-        run: rm -rf ./dist # 清理旧的构建目录
+      #   run: |
+      #     npm ci --legacy-peer-deps || { echo 'npm ci failed'; exit 1; } # 使用 npm ci 安装依赖
+        run: npm install
+      # - name: Clean dist directory
+      #   run: rm -rf ./dist # 清理旧的构建目录
       - name: Build
-        run: npm run build || { echo 'Build failed'; exit 1; } # 添加错误处理
+        run: npm run build # 构建项目
       - name: Setup Pages
         uses: actions/configure-pages@v3
       - name: Upload artifact
