fix: yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -39,9 +39,7 @@ jobs:
         run: npm cache clean --force # 清理 npm 缓存
       - name: Install dependencies
         run: |
-          for i in {1..3}; do
-            npm install --legacy-peer-deps && break || sleep 10
-          done # 尝试最多 3 次安装依赖
+          npm ci --legacy-peer-deps || { echo 'npm ci failed'; exit 1; } # 使用 npm ci 安装依赖
       - name: Clean dist directory
         run: rm -rf ./dist # 清理旧的构建目录
       - name: Build
